-- Healthcare AI Demo: Database, Schema, Warehouse, Roles Setup
USE ROLE ACCOUNTADMIN;

-- Create roles
CREATE ROLE IF NOT EXISTS HEALTHCARE_ADMIN;
CREATE ROLE IF NOT EXISTS HEALTHCARE_APP;

-- Grant Cortex database roles
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE HEALTHCARE_ADMIN;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE HEALTHCARE_APP;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_AGENT_USER TO ROLE HEALTHCARE_ADMIN;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_AGENT_USER TO ROLE HEALTHCARE_APP;

-- Grant roles to current user (replace <YOUR_USER> with your Snowflake username)
GRANT ROLE HEALTHCARE_ADMIN TO USER <YOUR_USER>;
GRANT ROLE HEALTHCARE_APP TO USER <YOUR_USER>;

USE ROLE HEALTHCARE_ADMIN;

-- Create warehouse
CREATE OR REPLACE WAREHOUSE HEALTHCARE_AI_WH
    WAREHOUSE_SIZE = 'MEDIUM'
    WAREHOUSE_TYPE = 'STANDARD'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for Healthcare AI Demo';

-- Create database and schema
CREATE OR REPLACE DATABASE HEALTHCARE_AI_DEMO;
CREATE OR REPLACE SCHEMA HEALTHCARE_AI_DEMO.CORE;

-- Grant privileges
GRANT USAGE ON WAREHOUSE HEALTHCARE_AI_WH TO ROLE HEALTHCARE_APP;
GRANT OPERATE ON WAREHOUSE HEALTHCARE_AI_WH TO ROLE HEALTHCARE_APP;
GRANT USAGE ON DATABASE HEALTHCARE_AI_DEMO TO ROLE HEALTHCARE_APP;
GRANT USAGE ON SCHEMA HEALTHCARE_AI_DEMO.CORE TO ROLE HEALTHCARE_APP;
GRANT ALL ON SCHEMA HEALTHCARE_AI_DEMO.CORE TO ROLE HEALTHCARE_ADMIN;

USE DATABASE HEALTHCARE_AI_DEMO;
USE SCHEMA CORE;
USE WAREHOUSE HEALTHCARE_AI_WH;
